[WASM] rust, wasm and better rust solutions
and some initial stats

although the "better" rust solution is broken due to the clone. it is
not returning the right answer and seems to return a different answer on
different machines?

  running 1 test
  test tests::it_works ... FAILED

  failures:

  ---- tests::it_works stdout ----
  thread 'tests::it_works' panicked at 'assertion failed: `(left == right)`
    left: `"00000014fafebf16c6f448c98937b393c0917cbf05e69a9b4ae428131b5e889c"`,
   right: `"00000ae1e9539146cffff9f6e177926993877055191da80dba6171711f33b363"`', src/lib.rs:67:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.