Convert from in memory to a real database
Had a bunch of issues following the text
- corresponding_question vs question_id in a bunch of queries
- not RETURNING id, content, corresponding_question" from insert
- comile errors between rust 1.73 and sqlx 0.7.4
  ```
  error[E0658]: `async fn` return type cannot contain a projection
      or `Self` that references lifetimes from a parent scope error:

  could not compile `sqlx-core`
  ```
    - https://github.com/launchbadge/sqlx/issues/2855#issuecomment-1798475204
    - updated with
      ```sh
      rustc --version
      rustc 1.73
      rustup update
      rustc --version
      rustc 1.78.0
      cargo --version
      cargo 1.78.0
      ```
- but got there in the end
- try:
    just
    just clean
    just setup-db
    cargo run
    just demo-crud